### ISSUE TITLE
rewrite or internal redirection cycle while internally redirecting to "/index.php"

### ISSUE THREAD

**Issue by esbenvb** [schliflo/bedrock-docker#9] opened 2018-07-02 21:09 UTC
I get this error in the web server log, when trying to access my newly set up WP site:

`web_1         | 2018/07/02 20:26:45 [error] 9#9: *8 rewrite or internal redirection cycle while internally redirecting to "/index.php", client: 172.18.0.2, server: jppol-blog.docker, request: "GET /favicon.ico HTTP/1.1", host: "jppol-blog.docker", referrer: "http://jppol-blog.docker/"`

I took a look in the config file for the site, and found a path which does not seem to exist on the server instance: `  root  /var/www/html/web;`

I'm not a wordpress, bedrock or docker expert at all, but this seems to be wrong?

```
$ make ssh web


/ # cat /etc/nginx/site.conf
server {
  listen [::]:80;
  listen 80;

  server_name jppol-blog.docker;

  access_log   /var/log/nginx/access.log main;
  error_log    /var/log/nginx/error.log;

  root  /var/www/html/web;
  index index.php index.htm index.html;
  add_header Fastcgi-Cache $upstream_cache_status;

  # Specify a charset
  charset utf-8;

  # Set the max body size equal to PHP's max POST size.
  client_max_body_size 25m;

  # https://www.nginx.com/resources/wiki/start/topics/tutorials/config_pitfalls/#virtualbox
  sendfile off;

  # Prevent PHP scripts from being executed inside the uploads folder.
  location ~* /app/uploads/.*\.php$ {
    deny all;
  }

  location / {
    try_files $uri $uri/ /index.php?$args;
  }

  include h5bp/directive-only/extra-security.conf;
  include h5bp/directive-only/x-ua-compatible.conf;
  include h5bp/location/cross-domain-fonts.conf;
  include h5bp/location/protect-system-files.conf;

  location ~ \.php$ {
    try_files $uri /index.php;

    include fastcgi_params;
    fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
    fastcgi_param DOCUMENT_ROOT $realpath_root;
    fastcgi_pass app:9000;
  }
}

# Redirect some domains
server {
  listen [::]:80;
  listen 80;
  server_name www.jppol-blog.docker;

  location / {
    return 301 http://jppol-blog.docker$request_uri;
  }
}

/ # ls -l  /var/www/html/
total 960
-rw-r--r--    1 root     root         32459 Jul  2 20:15 CHANGELOG.md
-rw-r--r--    1 root     root          3188 Jul  2 20:15 CODE_OF_CONDUCT.md
-rw-r--r--    1 root     root          1068 Jul  2 20:15 LICENSE.md
-rw-r--r--    1 root     root          5767 Jul  2 20:15 README.md
drwxr-xr-x    7 root     root           224 Jul  2 20:15 app
-rw-r--r--    1 root     root          1231 Jul  2 20:15 composer.json
-rw-r--r--    1 root     root         55932 Jul  2 20:15 composer.lock
drwxr-xr-x    5 root     root           160 Jul  2 20:15 config
-rw-r--r--    1 root     root        560191 Jul  2 20:15 package-lock.json
-rw-r--r--    1 root     root          3200 Jul  2 20:15 package.json
-rw-r--r--    1 root     root          2239 Jul  2 20:15 phpcs.xml
drwxr-xr-x   10 root     root           320 Jul  2 20:15 resources
drwxr-xr-x   15 root     root           480 Jul  2 20:16 vendor
-rw-r--r--    1 root     root        300522 Jul  2 20:15 yarn.lock
```

**Comment by schliflo** [comment] 2018-07-03 12:26
Seems like you used your own repository to get started. Bedrock-docker expects your repository to be created with the bedrock style: `composer create-project roots/bedrock`. You can use bedrock-docker to create such a project setup by pressing enter after running make up for the first time: 
```bash
Provide your own Bedrock repo or press enter to create a fresh instance:
Creating new Bedrock instance via composer
```

If you want to provide your own repository, it should look something like this:
```bash
/ # ls -l  /var/www/html/
total 44
-rw-r--r--    1 root     root          5055 May 18 23:19 CHANGELOG.md
-rw-r--r--    1 root     root          3188 May 18 23:19 CODE_OF_CONDUCT.md
-rw-r--r--    1 root     root          1044 May 18 23:19 LICENSE.md
-rw-r--r--    1 root     root          3976 May 18 23:19 README.md
-rw-r--r--    1 root     root          1609 May 18 23:19 composer.json
-rw-r--r--    1 root     root         16228 May 18 23:19 composer.lock
drwxr-xr-x    4 root     root           128 May 18 23:19 config
drwxr-xr-x   11 root     root           352 Jul  3 12:12 vendor
drwxr-xr-x    6 root     root           192 Jul  3 12:12 web
-rw-r--r--    1 root     root            13 May 18 23:19 wp-cli.yml
/ # ls -l  /var/www/html/web
total 8
drwxr-xr-x    8 root     root           256 Jul  3 12:14 app
-rw-r--r--    1 root     root           118 May 18 23:19 index.php
drwxr-xr-x   22 root     root           704 Jul  3 12:12 wp
-rw-r--r--    1 root     root           416 May 18 23:19 wp-config.php
```

I think the specific error you're running into is caused by not having the web folder where bedrock-docker would exprect it -> `/var/www/html/web`

Therefore index.php is not found and this somehow causes a redirection cycle.

I hope this helps resolving the issue. Feel free to ask if you're stuck again ;)

**Comment by schliflo** [comment] 2018-07-15 09:27
I'll close this for now. You can open a new issue if you're running into more problems.

**Closed as completed by schliflo** 2018-07-15 09:27 UTC
Labels: wontfix
